name: workshop_admin
description: A Flutter desktop admin app for fabrication tracking (Admin + Designer abilities).
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase (Desktop-ready; run: flutterfire configure)
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2


  # File/Excel handling
  file_picker: ^8.0.3
  excel: ^4.0.2

  # State management
  provider: ^6.1.2

  # Printing (PDF/Labels)
  printing: ^5.13.3

  # Utils
  intl: ^0.19.0
  path_provider: ^2.1.5
  share_plus: ^11.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
